name: Deploy Next.js App to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "15.x"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to AWS S3
        uses: actions/aws/cli@v2
        with:
          args: s3 sync ./out/ s3://aws-cdk-arachnet-s3 --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
