name: Deploy Next.js App to AWS S3

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "16.x"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region us-east-2

      - name: Deploy to AWS S3
        run: aws s3 sync ./out/ s3://aws-cdk-arachnet-s3 --acl public-read --delete
